export interface Product {
  id: string
  name: string
  category: 'cushions' | 'kitchen' | 'living-room'
  price: number
  image: string
  description: string
  longDescription?: string
  colors?: string[]
  featured?: boolean
  size?: string
  material?: string
  care?: string
}

export const products: Product[] = [
  {
    id: '1',
    name: 'Velvet Comfort Cushion',
    category: 'cushions',
    price: 49,
    image: '/products/cushion-1.jpg',
    description: 'Luxurious velvet cushion with premium filling',
    longDescription: 'Indulge in pure comfort with our Velvet Comfort Cushion. Crafted from premium quality velvet fabric, this cushion brings sophistication and coziness to any seating area. The plush filling provides exceptional support while the soft texture adds a luxurious touch to your home décor.',
    colors: ['Charcoal', 'Sage', 'Terracotta'],
    size: '18" x 18"',
    material: '100% Velvet, Polyester Filling',
    care: 'Surface clean only. Do not machine wash.',
    featured: true,
  },
  {
    id: '2',
    name: 'Linen Living Cushion',
    category: 'cushions',
    price: 45,
    image: '/products/cushion-2.jpg',
    description: 'Natural linen cushion perfect for any room',
    longDescription: 'Embrace natural elegance with our Linen Living Cushion. Made from sustainable linen fabric, it combines durability with effortless style. Perfect for creating a relaxed, inviting atmosphere in any room of your home.',
    colors: ['Beige', 'Navy', 'Clay'],
    size: '18" x 18"',
    material: '100% Linen, Feather Filling',
    care: 'Machine wash cold. Tumble dry low.',
    featured: true,
  },
  {
    id: '3',
    name: 'Organic Kitchen Cloth Set',
    category: 'kitchen',
    price: 28,
    image: '/products/kitchen-1.jpg',
    description: 'Set of 4 organic cotton kitchen cloths',
    longDescription: 'Keep your kitchen fresh and clean with our Organic Kitchen Cloth Set. Made from certified organic cotton, these cloths are gentle on surfaces yet highly absorbent and durable. Each set includes 4 versatile cloths perfect for daily kitchen tasks.',
    colors: ['Natural', 'Sage', 'Slate'],
    size: '18" x 18" each',
    material: '100% Certified Organic Cotton',
    care: 'Machine wash warm. Bleach if needed. Tumble dry.',
    featured: true,
  },
  {
    id: '4',
    name: 'Premium Tea Towels',
    category: 'kitchen',
    price: 32,
    image: '/products/kitchen-2.jpg',
    description: 'Sustainable tea towels with natural dyes',
    longDescription: 'Experience sustainable luxury with our Premium Tea Towels. Dyed with natural plant-based dyes, these towels combine eco-consciousness with exceptional absorbency and durability. Perfect for adding a touch of artisanal charm to your kitchen.',
    colors: ['Cream', 'Rust', 'Charcoal'],
    size: '22" x 28" each',
    material: '100% Organic Linen',
    care: 'Machine wash warm. Gentle cycle.',
    featured: true,
  },
  {
    id: '5',
    name: 'Woven Throw Blanket',
    category: 'living-room',
    price: 85,
    image: '/products/blanket-1.jpg',
    description: 'Hand-woven wool throw blanket',
    longDescription: 'Wrap yourself in warmth and comfort with our Hand-Woven Throw Blanket. Each piece is carefully crafted by skilled artisans using premium wool. The intricate weaving pattern adds visual interest while maintaining breathability for year-round use.',
    colors: ['Camel', 'Gray', 'Rust'],
    size: '50" x 60"',
    material: '100% Virgin Wool',
    care: 'Professional dry clean recommended.',
    featured: true,
  },
  {
    id: '6',
    name: 'Jacquard Table Runner',
    category: 'living-room',
    price: 65,
    image: '/products/runner-1.jpg',
    description: 'Elegant table runner with intricate pattern',
    longDescription: 'Elevate your dining experience with our Jacquard Table Runner. The intricate jacquard weave creates a sophisticated pattern that adds elegance to any table setting. Perfect for both everyday meals and special occasions.',
    colors: ['Gold', 'Silver', 'Bronze'],
    size: '13" x 72"',
    material: '68% Cotton, 32% Metallic Polyester',
    care: 'Machine wash gentle cycle. Air dry.',
    featured: true,
  },
  {
    id: '7',
    name: 'Quilted Decorative Cushion',
    category: 'cushions',
    price: 55,
    image: '/products/cushion-3.jpg',
    description: 'Modern quilted design cushion',
    longDescription: 'Add contemporary flair with our Quilted Decorative Cushion. The modern quilted pattern creates texture and visual depth, making it a perfect accent piece for sofas, beds, or reading nooks. Versatile in style, it complements any interior design.',
    colors: ['Cream', 'Sage', 'Charcoal'],
    size: '20" x 20"',
    material: '100% Cotton, Polyester Filling',
    care: 'Spot clean. Professional cleaning recommended.',
  },
  {
    id: '8',
    name: 'Linen Table Cloth',
    category: 'living-room',
    price: 75,
    image: '/products/tablecloth-1.jpg',
    description: 'Natural linen tablecloth for dining',
    longDescription: 'Transform your dining table with our Natural Linen Tablecloth. Made from premium quality linen, it offers a timeless elegance that works for both casual dining and formal occasions. The natural texture adds warmth and sophistication to any table setting.',
    colors: ['Flax', 'Dove', 'Charcoal'],
    size: '60" x 90"',
    material: '100% Pure Linen',
    care: 'Machine wash cold. Gentle cycle. Air dry.',
  },
  {
    id: '9',
    name: 'Cotton Dish Towels',
    category: 'kitchen',
    price: 24,
    image: '/products/kitchen-3.jpg',
    description: 'Soft cotton dish towels - pack of 6',
    longDescription: 'Stock your kitchen with our premium Cotton Dish Towels. This set of 6 offers excellent value without compromising quality. The soft, absorbent cotton makes them ideal for everyday kitchen tasks.',
    colors: ['White', 'Navy', 'Sage'],
    size: '16" x 26" each',
    material: '100% Cotton',
    care: 'Machine wash hot. Tumble dry medium.',
  },
  {
    id: '10',
    name: 'Embroidered Throw Pillow',
    category: 'cushions',
    price: 62,
    image: '/products/cushion-4.jpg',
    description: 'Hand-embroidered throw pillow',
    longDescription: 'Showcase artisanal craftsmanship with our Hand-Embroidered Throw Pillow. Each pillow features unique hand-embroidered details that add character and elegance. A true statement piece for any room.',
    colors: ['Beige', 'Rose', 'Indigo'],
    size: '16" x 16"',
    material: '100% Linen, Hand-Embroidered Details',
    care: 'Spot clean only.',
  },
  {
    id: '11',
    name: 'Damask Pattern Runner',
    category: 'living-room',
    price: 58,
    image: '/products/runner-2.jpg',
    description: 'Damask patterned decorative runner',
    longDescription: 'Add classic elegance with our Damask Pattern Runner. The timeless damask pattern brings sophistication to hallways, dining tables, or any space needing a touch of traditional beauty.',
    colors: ['Ivory', 'Gray', 'Taupe'],
    size: '13" x 60"',
    material: '70% Cotton, 30% Polyester',
    care: 'Machine wash gentle. Air dry.',
  },
  {
    id: '12',
    name: 'Bamboo Fiber Cloths',
    category: 'kitchen',
    price: 26,
    image: '/products/kitchen-4.jpg',
    description: 'Eco-friendly bamboo fiber cloth set',
    longDescription: 'Make an eco-conscious choice with our Bamboo Fiber Cloths. Made from sustainable bamboo fibers, these cloths are biodegradable and highly absorbent. Perfect for environmentally conscious kitchens.',
    colors: ['Natural', 'Gray', 'Blue'],
    size: '12" x 12" each (set of 4)',
    material: '100% Bamboo Viscose',
    care: 'Machine wash warm. Tumble dry low.',
  },
]
